Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/09/2024
Var
// Seção de Declarações das variáveis 
n,s : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
n <- 6
enquanto n<=100 faca
 s <- s+n
 n <- n+2
fimenquanto
escreva(s)
Fimalgoritmo